# Generated by Django 4.0.3 on 2023-12-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='hashtag',
        ),
        migrations.AddField(
            model_name='picture',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
