# Generated by Django 4.0.3 on 2023-12-11 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0002_remove_picture_hashtag_picture_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
