# Generated by Django 4.0.3 on 2023-12-11 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_photo_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='photo',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
